security:
    password_hashers:
        App\Entity\User:
            algorithm: auto # Bu, config/packages/security.yaml dosyasındaki aynı değer olmalıdır
            cost: 4 # bcrypt için en düşük değer
            time_cost: 3 # argon için en düşük değer
            memory_cost: 10 # argon için en düşük değer

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
                enable_csrf: false
            logout:
                path: logout
                target: login
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: form_login

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN]
